modLoader="javafml"
loaderVersion="[31,)"
# issueTrackerURL="http://my.issue.tracker/"

[[mods]]
modId="fightingdogs"
version="${file.jarVersion}"
displayName="Fighting Dogs"
authors="mintchkin"
# updateJSONURL="http://myurl.me/"
# displayURL="http://example.com/" #optional
# logoFile="examplemod.png"
description='''
Equip your canines with better fighting capabilities
'''

[[dependencies.fightingdogs]]
    modId="forge"
    mandatory=true
    versionRange="[31,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.fightingdogs]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
